* The First Law of Complexodynamics

The idea of this blog was to conjecture the first law of complextropy,
which was described as systems exhibiting the behavior of starting
with low complexity, reaching a large/peak complexity at intermediate
states, and returning back to small complexity for end states. This is
different from the laws of thermodynamics, specifically the second law
of thermodynamics, which essentially says that entropy montonically
increases in a system as time moves forward. The first law of
complextropy says that complexity rises at first, and then falls.

In order to have any way to prove this conjecture, the blog realizes
that measures for entropy and complexity must be fromally defined. For
these measures, they not only need to make sense as a proxy for the
ideas, but also must exhibit the desired behavior as conjectured. To
do this, the blog uses the theory of Kolmogorov complexity. The
Kolmogorov complexity of an object, such as a string, is the length of
a shortest computer program (written in some turing complete language
and verified by a Universal Turing Machine) that produces the object
as output.

To formally define entropy using its Kolmogorov complexity, the blog
notes that if we were examining a deterministic system, we could model
the upperbound growth rate for entropy of the system as a start
state + transition properties between time steps (constant number of
bits) and number of timesteps $t$ ($\log_2 t$ bits). So the upperbound
growth rate of entropy is logarithmic, which does not really agree
with human intuition that entropy increases at least linearly or even
at a polynomial rate (a human observing a system would assume that its
entropy at $t = 1000$ would be vastly larger than the system at $t =
0$, but this model for entropy would say that the two states have
almost identical entropy, only 10 bits of difference). To fix this
problem, we either consider systems to be probabilistic rather than
deterministic, or replace the Kolmogorov complexity by the
resoure-bounded Kolmogorov complexity: the length of the shortest
computer program that outputs the state in a short amount of time, or
the size of the smallest, say, depth-3 circuit that outputs the state,
which is a circuit that takes in some input (in this case, would be
the start state and $t$), and instantly output the result without ANY
loops. To do this, we would likely have to precompute the state of
entropy at time $t$ and bake it into the depth-3 circuit. The higher
the entropy, the more complex this baked-in state will be, leading to
the human intuited version of entropy that would increase at a
linearl/polynomial rate.

To formally define complexity, we use the notion of ``sophistication"
from Kolmogorov complexity. From the blog, this is described as the
following:

First, given a set $S$ of $n$-bit strings, let $K(S)$ be the number of
bits in the shortest computer program that outputs the elements of $S$
and then halts. Also, given such a set $S$ and an element $x$ of $S$,
let $K(x|S)$ be the length of the shortest program that outputs $x$,
given an oracle for testing membership in $S$ (or, in the case of this
question, the oracle can also answer back yes or no to any question
that you ask it, like if any string in the set is prefixed by <x'>).
Then we can let the sophistication of $x$, or Soph$(x)$, be the
smallest possible value of $K(S)$, over all sets $S$ such that

\begin{enumerate}
  \item $x \in S$ and
  \item $K(x|S) \ge \log_2(|S|) - c$ for some constant $c$. 
\end{enumerate}

Lets break this down. From this definition, sophistication is the
smallest computer program that can build the set $S$. What are the
properties of $S$? $S$ must be a set where $x$ is a completely random
element in $S$. Essentially, the idea is that the program $K(S)$ must
be able to describe all the non-random facts of $x$ perfectly. This
information is contained completely within the statement $K(x|S) \ge
\log_2(|S|) - c$. How you might ask. Before we answer this, we will
take a look at how the program $K(x|S$ will find $x$ the fastest given
an oracle. Lets assume $S$ only contains

Here, $c$ is the number of bits to create a prefix tree finder.

The blog finishes by saying that proving the first law of complextropy
is actually worthwhile, as it somehow is able to be used to decide
which theorems could be proved and which papers could be published,
though I don't really understand this yet.


