
* Overview

Notes for learning and remembering the emacs editor.

* Mode

** Major Modes

In Emacs, a major mode dictates the fundamental behavior of a buffer
(like a filetype in other editors). You can only run one major mode at
a time, and it governs how Emacs parses syntax, highlights code, and
executes specialized commands for that specific document type

** Minor Modes
Minor modes in Emacs are optional features that you can toggle on or

can activate multiple minor modes at the same time within a single
buffer. They provide localized enhancements, such as line numbers,
auto-saving, or spell-checking.

** Org Mode

Org Mode is a major mode in emacs. It allows for efficient editting of
org files.

*** Tasks

**** TODO Transfer all notes files to org-mode [0/1]               :@Misc:
- [ ] nvim.md

** Info Mode

*** Tasks
**** TODO Read Info#Advanced                                      :@Learning:

* Syntax table

This table is what emacs uses to keep track of meaning for every character. Mainly major modes will edit these syntax tables to define things such as "What charaters are used for comments" or "What charaters make up a word", although minor modes can provide (usually small) adjustments to this table.

** S-expressions

S-expressions (sexp) are important to undertand because they make movement much faster. An S-expression is the fundamental unit of syntax in elisp, and this is defined by the syntax table. They are typically:

- non-quoted words, including special characters
- numbers (eg. 42, 3.14)
- balanced expressions (eg. (), {}, <>, [])
- booleans

Moving by s-expression means moving to the end (start) of the next (previous) s-expression (of the same level, if balanced expressions are involved). Moving by list means moving to the end (beginning) of the next (previous) balanced expression, or the beginning of the child (parent) balenced expression. 

* Redo ring
* ELisp

** List Data Types

*** Printed Representation vs Read Syntax

The printed representation is the ouput of a type when elisp code is
evaluated, whereas the Read Syntax is a constant that the programmer
programs into the code to set a Symbol to some value

*** Char Syntax

Characters are integers under the hood. Using integers as read syntax
for characters is possible but not advised. The advised way to provide
read syntax for characters is by starting with a question mark

Ex:
?Q ; The letter Q, or ASCII value 81
?\N{LATIN SMALL LETTER A WITH GRAVE} ; à

The second is an example of escaping syntax. Read [[elisp#Basic Char
Syntax]] for more info on this.

*** Symbols

Symbols are the names of variables, functions, or property list.
Symbols starting with colon (':') are called "keyword symbols" and are
automatically constant. For more information about a symbols printed
representation and read syntax, read [[elisp#Special Read Syntax]]

*** Sequence Types

A "sequence" is a Lisp object that represents an ordered set of
elements. A list's length can be easily changed by adding or removing
elements, whereas an array's length is fixed.

*** Array Types

There are four array types: strings, vectors, bool-vectors, and char-tables. 

* Always Forget

** Movement
- C-f: Move forward one character
- C-b: Move backward one character
- C-n: Move forward one line
- C-p: Move backward one line
- C-e: Move to the end of the line
- C-a: Move to the fist white-space on the line
- M-f: Move forward one word
- M-b: Move backward one word
- M-e: Move to the end of the sentence
- M-a: Move to the end of the previous sentence
- M-m: Move to the beginning of the line
- C-v: Move forward one half screen
- M-v: Move backward one half screen 
- C-M-v: Move other window forward one half screen 
- C-M-S-v: Move other window backward one half screen
- C-M-f: Move forward by a s-expression
- C-M-b: Move backward by s-expression
- C-M-d: Move down into a list
- C-M-u: Move up out of a list
- C-M-n: Move forward to the next list
- C-M-p: Move backward to the previous list
- M-}: Move forward to end of paragraph
- M-{: Move backward to start of paragraph
- C-M-e: Move to next function declaration
- C-M-a: Move to previous function declaration

** Text Editing
- C-k: Delete till the end of the line
- C-/: Undo
- C-?: Redo
- C-.: Duplicate line
- M-u, C-M-k: kill-sexp
- C-u C-x u: Undo in region
- C-M-\: indents the marked region
- C-x C-q: Toggle read-only mode
  
** Searching

- C-s: Begins an incremental search
- C-r: Begins a backward incremental
- C-s C-w: Search for the word underneath the cursor
- C-M-s: Begins a regexp incremental search
- M->: Jump to the last match
- M-<: Jump to the first match

** Documentation/Help

- C-h pt: Opens the interactive Emacs Tutorial to learn basic editing commands.
- C-h k: Prompts you to press any key combination and explains what command it runs.
- C-h f: Looks up and displays the documentation for a specific Emacs function or command.
- C-h v: Shows the documentation and current value for a specified configuration variable.
- C-h a: Performs an "apropos" keyword search to list matching commands and functions.
- C-h b: Lists all active keyboard shortcuts (key bindings) available in your current file or mode.
- C-h i: Launches the built-in Emacs Info Manual reader for full, structured guides.
- C-h C-h: Opens a comprehensive help screen listing every single available help option.
- M-x list-packages: Lists all downloadable packages (with melpa?)

** Registers

- C-x r m: Add a bookmark
- C-x r l: Opens bookmark interactive list
- C-x r b: Jump to bookmark
- C-x r n: Store number in register
- C-x r s: Store region in register
- C-x r SPC: Store point in register
- C-x r +: Increment number in register
- C-x r j: Jump to register
- C-x r i: Insert content of register
- C-x r w: Store window configuration in register
- C-x r f: Store frameset in register

** Mark

- C-SPC: set a mark and enter transient mark mode
- C-u C-SPC: return to the previous mark in the mark ring
- C-SPC C-SPC: 
- C-x C-x: Swap the previous mark and point, and reactivate the last
  region if it exists

Percise marking:

- M-h: Marks the next paragraph
- C-x h: Marks the whole buffer
- C-M-h: Marks the next defun
- C-x C-p: Marks the next page
- M-@: Marks the next word
- C-M-<SPC>, C-M-@: Marks the next s-expression

** Dired

- C-x d: open dired
- C-x C-f: Finds a file, and creates it if it does not already exist
- R: rename a file/directory
- +: Add a new directory
- C: copy the file to a target directory

** Terminal
- M-!: execute a raw bash command
- C-u M-!: inserts the output of the shell command at the cursor position
- M-&: Runs a shell command asynchronously in the background. Use for long running commands so that emacs doesn't freeze.
- M-|: Sends highlighted text selection as standard input to a shell command. Ex: Highlighting a list and passing it to the "sort" command will return the sorted list.
- C-u M-|: Sends highlighted text selection as standard input to a shell command and replaces the highlighted region with the output of the command.
- M-x vterm: open an interactive shell
- C-c C-t: enter vterm-copy-mode, which freezes the terminal output and lets you use the buffer like any other buffer in emacs.

** formatting

- C-M-\: auto-indent the highlighted region

** Windows + Buffers

- C-x 2: Horizontal Split
- C-x 3: Vertical Split
- C-x 4: opens a new window for the following 
- C-x C-s: Save current buffer
- C-x s: Save all open buffers (with confirmation)

** tab-mode

- C-x t 2: Create a new tab
- C-x t 0: Close the current tab
- C-x t RET: Select tab by name
- C-<tab>, C-x t o: Next tab
- C-S-<tab>: Previous tab
- C-x t r: Rename tab
- C-x t p ...: Run project command in other tab
- C-x t t: Execute command in other tab
- C-x t 1: Close all other tabs
- C-x t C-t, C-x t C-f: Find file in other tab
- C-x t b: Switch to buffer in other tab
- C-x t d: Open dired in other tab
- C-x t l: Show interactive tab list

** tab-bar-history-mode

- M-[: go back to a previous window configuration in the current tab
- M-]: cancel restoration of the privious window configuration
** Org Mode

*** Styles

Wrap text with the following to achieve their styles:
- *: Strong emphasis
- /: Slanted emphasis
- =: Verbatim
- ~: Code
- _: Underline
- +: Strikethrough
  
*** Tasks

- C-c a: open org-agenda.
- C-c c: Capture a thought/task
- C-c C-c: toggle a TODO checkbox.
- C-c C-s [+n]: schedule a task n days in the future (default 0).
- C-c C-d [+n]: deadline a task n days in the future (default 0).
- C-c C-t: toggle a TODO Header.
- C-c C-x a: archive a TODO (toggle).
- C-c C-x C-i: Clock-in to a task
- C-c C-x C-o: Clock-out of a task

*** Folds/Structured Elements

- M-<up> / M-<down>: Move a structured element up or down
- TAB: Cycle through folding layers for a structured element
- S-TAB: Cycle through folding layers for all headers only
- M-RETURN: Create another structured elementp
- C-RETURN: Create another Header element
- M-<right> / M-<left>: Promote or demote a structured element
- M-S-<right> / M-S-<left>: Promote or demote a structured element and
  all its children
- S-<right>: Smart switch the type of structured element

*** Others
p- [link][description]: Link
- C-c C-,: Insert a structure template (block structure)

** Info Mode

- n: move to the next node at that level in the tree.
- p: move to the previous node at that level in the tree.
- u: move to the ancestor node of the current node.
- <SPC>: move a page down. If at the end of the node, move to the next child node of the current node, or the next child node of its near
- <BACKSPACE>: move a page up. If at the start of the node, move to the previous child node of the nearest ancestor that has a previous child node.
- ]: Works the same as <SPC> when at the end of the node without needing to be at the end of the node.
- [: Works the same as <BACKSPACE> when at the beginning of the node without needing to be at the beginning of the node.
- <TAB>: move the cursor over the next menu subtopic
- f [PATTERN]: finds the cross-reference node with the name PATTERN
- l: move backwards in the list of recently visited nodes
- r: move forwards in the list of recently visited nodes
- L: list the entire history of visited nodes
- d: Get the directory node
- t: Get the top node of the current manual (one level lower than the directory node).

** Macros

- C-x (: Start recording a macro
- C-x ): Stop recording a macro
- C-x e: Play recorded macro

** Magit

RET: Visit things. Magit is very smart about this.

*** Movement
- n: go to next section
- p: go to previous section
- C-x C-j: dired jump

*** Diff
- d: 
- C-c C-t: Get the history of a function definition from the diff
- C-c C-e: Edit the contents of a diff. This could be a diff that
  isn't currently on your computer, i.e. a diff from a previous commit
- E: Ediff (look at man pages for more)

*** Folds
- 1-4: Change visibility of the fold (1 is least visible, 4 is most visible)
- g: reload the magit status window
- G: reload all files in the git repo?
- j: jump to section

** Fido
- M-j: accepts the bect currently typed in the minibuffer as is
